### ISSUE TITLE
string literals dont account for CRLF

### ISSUE THREAD

**Issue by Orcolom** [wren-lang/wren#988] opened 2021-04-24 12:45 UTC
![image](https://user-images.githubusercontent.com/10909816/115959231-7b7dd700-a50b-11eb-962f-809fc8eadf13.png)

**Comment by Orcolom** [comment] 2021-05-09 11:21
Using this code

```js
System.print("a string") // expect: a string

var long = "
  A
  multi line
  regular string
"
System.print(long) // expect: 
                   // expect:   A
                   // expect:   multi line
                   // expect:   regular string
                   // expect: 

var raw = """
  A if*(<invalid>)*
  multi line /{}()
  raw string [\]/
  "json": "value"
"""
System.print(raw) // expect:   A if*(<invalid>)*
                  // expect:   multi line /{}()
                  // expect:   raw string [\]/
                  // expect:   "json": "value"
```

return results are 
```
"a string"
"\n"

"\r\n  A\r\n  multi line\r\n  regular string\r\n"
"\n"

"\r\n  A if*(<invalid>)*\r\n  multi line /{}()\r\n  raw string [\\]/\r\n  \"json\": \"value\"\r"
"\n"
```

observations:
1. both multi line strings and raw strings have the `\r` show up
2. raw multi line string starts with `\r\n`
3. raw multi line strings has a trailing `\r`


I did a small test where I change every instance of `\r\n` to `\n`.  It gave me some failed tests with trimming, but I haven't had the time to check why

So, at the very least point 2 and 3 should be fixed to adhere to wren standards.

But i do have a question if we should keep or remove `\r\n` to simplify working with strings across platforms

**Comment by joshgoebel** [comment] 2021-05-09 11:31
What are "wren standards" here again?  If we're using \r\n for newlines (inside raw strings) in general then then example 3 seems broken to me, in that it should end in `\r\n` to be consistent with everything else.

**Comment by Orcolom** [comment] 2021-05-09 11:44
Standard was wrong word, I mean mainly "what is expected behaviour"

From my understanding both the leading and trailing newline should have been ignored in the raw string

**Comment by joshgoebel** [comment] 2021-05-09 12:03
OH, are you actually putting literal \r and \n characters there and then expecting them to come back verbatim?  I guess I wasn't thinking of invisibles or special chars... So I guess raw to me was "mostly raw" not "any binary characters at all"... so I think the expected behavior may indeed need to be clarified.

>  This means the opening and closing lines are not counted as part of the string when the triple quotes are separate lines, as long as they only contain whitespace (spaces + tabs).

It does seem to say only spaces and tabs are whitespace, not `\r`.

**Comment by joshgoebel** [comment] 2021-05-09 12:05
I do think it would be very weird though if the string was TRULY RAW... meaning that depending on the platform (Windows, Unix, etc) the value of the string changes depending on whether CR or CR+LF was used... that seems more than a little problematic...  I would certainly NOT expect that behavior.

**Comment by ruby0x1** [comment] 2021-05-09 19:16
In a regular string, \r is an [escape sequence that emits](https://github.com/wren-lang/wren/blob/main/src/vm/wren_compiler.c#L1018) \r. In a raw string escape sequences don't exist.

Ordinarily wren treats \r in the input (not inside a string) [as whitespace](https://github.com/wren-lang/wren/blob/main/src/vm/wren_compiler.c#L1165-L1171). 

While parsing a raw string, there's logic to ignore the whitespace on the same lines as the delimiter. The [raw string only considers](https://github.com/wren-lang/wren/blob/main/src/vm/wren_compiler.c#L922) `'\t'` and `' '` to be whitespace. To make the raw string consistent with the language parsing and across line endings, you would want to just add `|| c == '\r'` to the `isWhitespace` check in `readRawString`. That should treat `\r\n` inside the start of a raw string as it should and ignore it.

I think that's the only issue showing here, that raw strings don't count `\r`. That and the tests should include `\r\n` being ignored for raw strings as expected.

**Comment by joshgoebel** [comment] 2021-05-10 02:44
> I think that's the only issue showing here

So to be clear... a script being saved as CR, CRLF, or LF could entirely alter the behavior of a Wren program that uses raw strings?  That behavior is correct and intentional?  Yes, I'm using the CLI here but surely _multiple_ Wren projects store the Wren source in text form and then load it and pipe it into Wren (even if Wren itself isn't doing the file I/O)...  TIC-80 does this for sure, just to name one project.

**The behavior that we now**

```
% dos2unix cr.wren                        
dos2unix: converting file cr.wren to Unix format...
% ./bin/wren_cli cr.wren
33
% unix2dos  cr.wren                       
unix2dos: converting file cr.wren to DOS format...
% ./bin/wren_cli cr.wren
37
```

The source of `cr.wren`:

```
var a = """
Just a test string.
nothing more.
"""
System.print(a.count)
```

**The expected behavior**

The output number _does not change_ regardless of the line ending used to save the input source.

**Comment by ruby0x1** [comment] 2021-05-10 02:51
I wasn't implying this was expected🤔I was pointing out the location of the issue/inconsistency and saying it's an issue. And that we need tests to ensure the consistency.

**Comment by joshgoebel** [comment] 2021-05-10 03:02
I feel like perhaps we aren't talking about the same "this".  The way I read your response was that it was _only_ addressing the whitespace stripping behavior at the string beginning and end... I did not see where you addressed the large point I raised about the overall content of the string processing being ambiguous depending on the line endings (which seems problematic).

>  that raw strings don't count \r

Maybe this is related, but it's not only the count that matters (though that would fix my tiny example).  If someone is iterating over the string byte by byte I'm asking for clarification on whether the content of lines should vary depending on whether the content was saved CR/LF/CRLF... If you've clarified that I'm not seeing it.

Would you prefer I open a separate issue vs mixing that with this issue?

**Comment by ruby0x1** [comment] 2021-05-10 03:35
To reduce confusion, how does a non-raw string behave?

```js
var a = "
Just a test string.
nothing more.
"
System.print(a.count)
```

**Comment by joshgoebel** [comment] 2021-05-10 04:26
Seems to have the same behavioral issue as with raw strings: behavior is dependent on whether the file/input stream has CR, LF, or CRLF line endings.  This seems to be a unique bug (or feature) of Wren compared to other languages I have experience with (and I'd guess most languages).

I wrote similar test programs in...

Ruby

```rb
a = "
test
test
more
"
puts a.length
```

Node.js

```js
var a = `
asdasd
adasd
asdasd
`;
console.log(a.length)
```

Python3

```py
a = """
test
test
test
"""
print(len(a))
```

The behavior is 100% consistent in all 3 languages _regardless of line ending encoding_.  Line endings (inside the runtime) seem to always be resolved to `\n` regardless of how they appear on-disk or in the input stream.  I would guess this happens at input time (when reading the files) but I'm just guessing.

**Comment by ruby0x1** [comment] 2021-05-17 22:00
While the fix for CRLF inconsistency is trivial and will land soon, there's a bit of nuance in the situation due to how wren core is embedded. It's surprising we never noticed this before, but it will be good to make the behaviour consistent. **In a near-future commit strings will be normalized to `\n` only in the presence of `\r\n`.** 

Nuance: The wren core .inc files don't escape string escapes, so they end up being converted to literals in the source, which breaks things when this is fixed. 

Specifically, wren core has e.g string trim, which uses a literal string `"\t\r\n "`. In the wren file, these are string escapes. In the wren_core.wren.inc file they are no longer escapes destined for the wren vm, but instead are escapes interpreted by the C compiler, which converts them directly to literal characters. So the wren vm executes a string containing those as literal characters, rather than a string containing escapes.

I'm fixing that behaviour and then this fix will work as intended. 

Thanks for testing some other languages, I had also done so while testing.  Not many seem to document this normalization, at least that I could find with a quick search, [though rust mentions](https://doc.rust-lang.org/reference/tokens.html#string-literals) "Both byte sequences are normally translated to U+000A". 

And funny enough, immediately after reading the description of the issue, on my new PC git decided to checkout my repo and convert everything to CRLF (no idea why this is a default), which broke my raw strings for docs/completion, showcasing the issue.

**Comment by joshgoebel** [comment] 2021-05-17 22:08
> Thanks for testing some other languages ... Not many seem to document this normalization

Glad to help.  I guessed that it would be easier to just test it than to try to find docs on this. :-)

>  git decided to checkout my repo and convert everything to CRLF

Can this be resolved permanently with `.gitattributes` or someting?  And perhaps it's time to mention yet again [editorconfig](https://github.com/wren-lang/wren/pull/846) as a way of keeping us all on the same page with these things.

**Comment by ruby0x1** [comment] 2021-05-21 23:32
The issue with CRLF significance should be fixed now. All tests pass regardless of the newline formats, and I've added a note to the docs on the values page to note that they're normalized (which should be live soon).

**Closed by ruby0x1** 2021-05-21 23:32 UTC

**Comment by joshgoebel** [comment] 2021-05-22 00:32
Worth pointing out this removes all `\r`, not just `\r` in `\r\n` combos...  I assume that's fine though and if someone wanted `\r` (in a normal string) they should escape it with `\`?

**Comment by ruby0x1** [comment] 2021-05-22 00:33
Not a concern atm yea.
